### ISSUE TITLE
Alert messages don't automatically disappear?

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#158]
I could see the case for leaving this as a feature, but if there are many error messages then they pile up at the top.

**Comment by drenfr01** [comment]
per Laura and Eric's feedbac, let's time out the success messages but leave the error ones

**Comment by drenfr01** [comment]
@ballek can you confirm this happens in Production Laura?

**Comment by ballek** [comment]
@drenfr01 
![img_7675](https://cloud.githubusercontent.com/assets/7898004/8214847/1598ec06-14fa-11e5-8c15-32ad09f897a4.JPG)

this guy's been sitting pretty for about 3 minutes now

**Comment by drenfr01** [comment]
we need to just switch to sAlert here...
