### ISSUE TITLE
Events created do not go to super Admin events viewer

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#159]
![screen shot 2015-05-22 at 1 06 37 pm](https://cloud.githubusercontent.com/assets/7898004/7775719/8159df12-0083-11e5-919d-af4cd2ffcf53.png)
![screen shot 2015-05-22 at 1 06 43 pm](https://cloud.githubusercontent.com/assets/7898004/7775720/83b1655a-0083-11e5-95fb-717e8ee2cf9c.png)

although the event *does* pop up in the user calendar

**Comment by TylerSheffels** [comment]
@ballek I think this is just #166 and you have to click on the past events toggle.

**Comment by ballek** [comment]
@TylerSheffels indeed you are correct sir
