### ISSUE TITLE
Camera Functionality Not Working

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#160]
Android 4.1.2, Chrome Browser
-Working as user
-Auto check-in
![img_7587](https://cloud.githubusercontent.com/assets/7898004/7775841/98c03682-0084-11e5-84a9-13752d498e60.JPG)

**Comment by drewproud** [comment]
@ballek - can you record the model of phone as well?

**Comment by ballek** [comment]
sure! this is model number Z740

**Comment by ballek** [comment]
![img_7589](https://cloud.githubusercontent.com/assets/7898004/7776145/b8c0edda-0086-11e5-8e1f-7bbe9f681e05.JPG)

**Comment by drewproud** [comment]
The fix is now in master. I'll leave this issue open until we can test and confirm.

**Comment by drenfr01** [comment]
The fix allowed an Iphone 6 with Safari to work with the camera (previously it throw a "Browser does not support a feature" popup message).

Will need to retest with more phones to close this bug

**Comment by ballek** [comment]
last night this seemed to work with a lot of phones! good job guys! i'll go to bocoup again to test with more phones, but there were no major issues last night

**Comment by drenfr01** [comment]
@ballek did your additional testing uncover anything here?
