### ISSUE TITLE
CSV Events Upload

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#161]
Events are recognized! Woo-hoo!

![screen shot 2015-05-22 at 1 41 26 pm](https://cloud.githubusercontent.com/assets/7898004/7776370/5f6c3de6-0088-11e5-8a4a-d6566d23b5b0.png)

However, when pressing submit, nothing pops up and events do not appear to enter the events listing.

**Comment by TylerSheffels** [comment]
@ballek Should be fixed now

**Comment by drenfr01** [comment]
@ballek please retest then we can close it (I think that's what tyler meant above)

**Comment by ballek** [comment]
@TylerSheffels FUCK YEAH IT WORKS!!!!! i think i was just an idiot and forgot to put the times in, so it probably worked while i was making this bug but FUCK YEAHHH nonetheless!
