### ISSUE TITLE
Put in better description / placeholder for Google autocomplete address in the sign up

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#176]
It's not intuitive that the sign up expects you to enter a partial address than use the autocomplete suggestions.

**Comment by drenfr01** [comment]
![screen shot 2015-05-28 at 8 04 10 pm](https://cloud.githubusercontent.com/assets/508707/7873785/baa6cc3a-0574-11e5-851e-4a4e74c65f94.png)

**Comment by drenfr01** [comment]
This was pointed out by Lisa, what do you think @ballek

**Comment by ballek** [comment]
does it populate a dropdown? since we're going to be walking people through this process it's not so very critical
