### ISSUE TITLE
Add in "transactions" as a downloadable CSV to Export Data for both partners and super admin

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#186]
Right now there's no way to get at what users have participated in what events through downloadable CSVs.

This is a little trickier than just grabbing the transactions collection though, we will need to denormalize some basic event and user info into it to make it usable for data analytics.

**Comment by drenfr01** [comment]
This should be way easier with events denormalized into transactions. Not to mention faster

**Comment by ballek** [comment]
george and i talked about this one- 

every partner would only be able to download their own members' data, so anyone who has them listed as a 'partnerOrg' would be included. 

then select a time range (we based on eventDate, not transactionDate) and click download

not all fields are necessary- the ones we thought would be good were 'hoursSpent, approved, event.name, event.address, event.institution, event.category, firstName, and lastName'

@drenfr01 @drewproud
