### ISSUE TITLE
Change "Future Events" to "Next Week", change past events to "Last Week" on Events Calendar for members

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#189]
We should probably also have a "Today's events" section, which is events happening today.

**Comment by ballek** [comment]
will members be able to see events far into the future? i think at least a month or two would be ideal. in that case, should we keep "future events" as it is?

**Comment by drewproud** [comment]
@ballek it currently is set to look into the future 7 days, but can easily changed via a configuration value. How many days do you want it set to? Agreed on your second point.

**Comment by drewproud** [comment]
I left the text and 'Future Events' and 'Past Events'. Leaving this ticket open until we tweak the config per Laura's wishes.

**Comment by ballek** [comment]
@drewproud you're going to make me go mad with power!!!! how about 6 weeks? that gives users a month and a half to plan for

**Comment by drenfr01** [comment]
closing this issue
