### ISSUE TITLE
Data type errors with both duration of event and the amount of time spent

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#193]
For whatever reason, it looks like we round / have as integers the duration of the event and the amount of time someone spent at it (i.e. setting the UI slider on the event details check in screen).

We tried to enter 1.5 hours for a points per hour event that was worth 200 points, and got 200 points instead of the expected 300.

Likewise the duration of the event appeared cut off

**Comment by drenfr01** [comment]
also saw during event approval that it listed the events as an int, e.g. it said 1 hours instead of 1.5, or 0 instead of 0.5 for the amount of time someone spent at the event.

**Comment by drewproud** [comment]
Fixed.
