### ISSUE TITLE
streamline check-in?

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#198]
can we switch normal check-in to remove the select button and just go straight to check-in? 
![screen shot 2015-06-03 at 6 45 57 pm](https://cloud.githubusercontent.com/assets/7898004/7973187/f990fa5a-0a20-11e5-90d5-7334cc09d6bc.png)
![screen shot 2015-06-03 at 6 46 04 pm](https://cloud.githubusercontent.com/assets/7898004/7973188/fbde6004-0a20-11e5-92b9-26d4107ba8a0.png)

it looks great on the past event!
![screen shot 2015-06-03 at 6 46 28 pm](https://cloud.githubusercontent.com/assets/7898004/7973195/0e8318ee-0a21-11e5-884e-916a7c0ff16a.png)

**Comment by drewproud** [comment]
@ballek that can be done! What priority should we tag this with?

**Comment by drenfr01** [comment]
@ballek @drewproud Let's hold on this until we get past Saturday. It's more of a nice to have than a bug / necessary enhancement

**Comment by drenfr01** [comment]
this has now been fixed with the new 3.0 checkin flow
