### ISSUE TITLE
Members signed up but are missing from the admin members list

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#200]
Liz Reed
Saundra Greene
Sylvia Brewer
Lorraine Jones

these four members have created accounts but do not show up on the admin members list

**Comment by drewproud** [comment]
This should be good to go after next deploy. It was limiting the members data at 20 when it sent it up. Until then, you can still search for the user and they'll show up.

**Comment by ballek** [comment]
As we add in more members and have a great number of them, will it be possible to add pagination for faster loading?
