### ISSUE TITLE
Replace current URL for modulus with ucbapp.org

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#206]
Right now ucbapp.org exists only as a re-direct to the modulus sites, http://unioncapital-42343.onmodulus.net/.

Ideally this redirect wouldn't happen and ucbapp.org would just be the name, because it's confusing to our users (feedback from Eric).

**Comment by drewproud** [comment]
Done. The main site is www.ucbapp.org, and ucbapp,org redirects to the www subdomain.
