### ISSUE TITLE
Sort function in Admin-Member isn't working in

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#210]
Ascending/Descending sort does not work for any of the categories. Points in Red is selected but points are not sorted
![untitled](https://cloud.githubusercontent.com/assets/7445103/8146660/1c774e8e-1214-11e5-8923-056f14862f92.png)

**Comment by drewproud** [comment]
Fixed in latest pull request.

**Comment by drenfr01** [comment]
@ballek please test in QA

**Comment by ballek** [comment]
@drenfr01 the only weird thing i can find is that it seems to handle uppercase and lowercase letters differently- otherwise, it works!
![screen shot 2015-06-17 at 2 40 43 pm](https://cloud.githubusercontent.com/assets/7898004/8215598/04c4c576-14ff-11e5-84ef-9cb65bd23e89.png)
