### ISSUE TITLE
Please change all notifications and queries to: contact@unioncapitalboston.com

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#212]
Members are confused that their emails are coming from Duncan
![untitled](https://cloud.githubusercontent.com/assets/7445103/8146686/2590b478-1215-11e5-8e90-ee73ca4dba69.png)

**Comment by drenfr01** [comment]
correction, I believe this was fixed by adding admin email to app config. thanks @drewproud !

**Comment by drenfr01** [comment]
@ballek do you think this is closed?

**Comment by ballek** [comment]
@drenfr01 definitely works for comments, still waiting on the initial signup email to see if that works.

**Comment by unioncapitalboston** [comment]
This is still not working for Comments or Initial Signup Email :(

**Comment by drenfr01** [comment]
I think we need to change the email credentials to something like mailgun or contact@unioncapital.com

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek  looks like we may need to setup a new domain to actually send emails through smtp (based on a bit of research). It doesn't look like we can send emails through aliases. 

https://productforums.google.com/forum/#!topic/apps/vGILoFCHQ44

**Comment by ballek** [comment]
@drenfr01 is now the time for a full migration to ucbapp.org? we should be able to send emails through that, no?

**Comment by drenfr01** [comment]
Errr...what do you mean by that?
