### ISSUE TITLE
Please add a space after the punctuation in the Notification comments

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#213]
![untitled](https://cloud.githubusercontent.com/assets/7445103/8146688/792bf7b4-1215-11e5-8bd2-9666378d5bdb.png)

**Comment by drenfr01** [comment]
@unioncapitalboston errr...where now?

**Comment by drenfr01** [comment]
@ballek do you know what this is?

**Comment by ballek** [comment]
@drenfr01 shhhh i'm going to quietly close this one because i don't see it either
