### ISSUE TITLE
Limit images to only publishing a subset of it

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#214]
Currently we publish all images, which is probably only reasonable for the superadmin.

**Comment by drewproud** [comment]
@drenfr01 this may not actually be the case... I think Images.find(id).url() is the method that actually requests the image and loads it. We may be okay here, though we should keep an eye on bandwidth usage as more users sign up.

**Comment by drenfr01** [comment]
@drewproud  Okay, sounds good. At some point we'll probably want Kadira anyway
