### ISSUE TITLE
Can "Comments" arrive from the Account Member email address instead of Duncan?

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#215]
When a User submits a comment, can it be tagged to their email address instead of Duncan? In this example, the email would have come from kslovesu2@gmail.com
![untitled](https://cloud.githubusercontent.com/assets/7445103/8151437/4e4b5fb4-12db-11e5-94ae-d70d64b79b01.png)

**Comment by drenfr01** [comment]
@ballek mind testing this after we push the code into QA? basically you'll create a user with your email address, send a comment, and make sure the from email address is correct

**Comment by ballek** [comment]
@drenfr01 seems to be working from the modulus log!
