### ISSUE TITLE
User submitted Event with no Category - now it can't be Approved

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#216]
Somehow LaChynae Loving submitted a Selfie Event without selecting a Category. I am now unable to approve the event because there was no Category. Can this be fixed so that all events have to select a Category?
![untitled](https://cloud.githubusercontent.com/assets/7445103/8168461/e81f3b5c-1370-11e5-9875-bd08e8b7d5fe.png)

**Comment by drenfr01** [comment]
put in a fix, testing in QA

**Comment by ballek** [comment]
@drenfr01 @TylerSheffels I tested in QA, seems to be all set... However, can we have consistency in error messaging? plz see below
![img_7676](https://cloud.githubusercontent.com/assets/7898004/8214970/fa89c97a-14fa-11e5-993c-6174fef689d9.JPG) (missing event category)
![img_7677](https://cloud.githubusercontent.com/assets/7898004/8214975/053f22a2-14fb-11e5-8894-16adb5fa70f0.JPG)(missing event date)

![img_7678](https://cloud.githubusercontent.com/assets/7898004/8214979/0c00efe4-14fb-11e5-94c0-4df4e57e3d0a.JPG)(missing description)

**Comment by drenfr01** [comment]
Ahh, so @ballek  you'd like event description to have the same message as the other two, correct?

**Comment by ballek** [comment]
@drenfr01 yes please if ya don't mind! ^__^
