### ISSUE TITLE
Photo Album photos not uploading?

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#223]
I took a photo of reading with my daughter and then created the event. I attached the photo from my iPhone Photo Album and the entry displayed that the photo had been uploaded. I went to go approve the event and it says "No Image Found". Is this because it was pulled from the Album and taken previously, instead of using the camera? Is this a bug that can be fixed?
![untitled](https://cloud.githubusercontent.com/assets/7445103/8222410/f03eacd6-1538-11e5-8eb9-4e8edeec82e0.png)

**Comment by drenfr01** [comment]
@unioncapitalboston  was this on QA or Prod?

**Comment by ballek** [comment]
@drenfr01 I believe Eric was using this on Prod
