### ISSUE TITLE
Archived members are still showing in Member List

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#228]
Zulma Morales created two accounts. I archived the blank one last week but it is still showing in the Member List. So is my original account too - there are two Eric Leslie accounts - I tried to archive the NaN account last week.
![untitled](https://cloud.githubusercontent.com/assets/7445103/8284064/e4fef90a-18c8-11e5-8710-7466d6244849.png)

**Comment by drewproud** [comment]
@unioncapitalboston it appears that this functionality is by design - it even gives you the ability to unarchive members if you click on their name. Should we remove it?

**Comment by drenfr01** [comment]
@ballek ?

**Comment by unioncapitalboston** [comment]
Let's remove it! :)
