### ISSUE TITLE
Email addresses are case sensitive - can that be changed?

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#229]
When I try to login using my email address as ericrl26@aol.com it says "User does not exist" but logs me in with EricRL26@aol.com

**Comment by drenfr01** [comment]
Need to figure out how to make all existing members email addresses lower case

**Comment by drenfr01** [comment]
Marking this as critical only because the fix is in master, and in order to deploy v2.2. we need to make this happen

**Comment by drenfr01** [comment]
@ballek  @TylerSheffels  anyone know how to test this in Prod? I think we can close it after that

**Comment by TylerSheffels** [comment]
A quick glance through the db shows no emails with capitals, I think good,
but you could always create a user with capitals in the name

**Comment by ballek** [comment]
@drenfr01 @TylerSheffels tested in prod, good to go!
