### ISSUE TITLE
Geolocation not working or range not large enough?

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#230]
I was at a pre-entered and verified event tonight and submitted while at the location. It did not automatically process for points when I checked in even though it should have. Is this because the geolocation is not processing at the moment or the range is not large enough? If it seems to be a range issues, maybe we should increase it to 200 yards?
![img_4433](https://cloud.githubusercontent.com/assets/7445103/8297085/3fa9950a-1927-11e5-9a17-7cd38886d732.png)
![img_2683](https://cloud.githubusercontent.com/assets/7445103/8297090/5d2f191a-1927-11e5-85dd-20819cd96944.png)

**Comment by drewproud** [comment]
It appears that it was out of range. Here's where your geolocation had you placed. We currently have the max distance set to 100m -  we can can this if need be.

![screenshot from 2015-06-22 22 30 42](https://cloud.githubusercontent.com/assets/4421460/8297790/927f6c9e-192e-11e5-883c-85068973955c.png)

**Comment by drenfr01** [comment]
@unioncapitalboston @drewproud @ballek  I'm just going to bump this to 200m and see if that helps

**Comment by unioncapitalboston** [comment]
Yay! 200 meters - let's do it! Thanks Team :)

**Comment by drenfr01** [comment]
updated to 200m, and will be in 2.1.1
