### ISSUE TITLE
Two submissions occurred for the same event

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#233]
The first event had a photo attached, the second one didn't. Any way to prevent this double submission from happening?
![untitled](https://cloud.githubusercontent.com/assets/7445103/8321941/b52157d0-19fb-11e5-8bea-388ab91f477d.png)

**Comment by drenfr01** [comment]
This is a duplicate

**Comment by drewproud** [comment]
How fitting.
