### ISSUE TITLE
Can we add column for Date of Event, not just date entered?

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#234]
Because we now have a one week time limit for Event entry, can we add in a column in Admin Pending Transactions for Date of Event selected, not just the date/time the event was submitted? A couple of people have submitted for events in early June but I have not been able to catch it because there is no Event Date column visible. Thank you!
![untitled](https://cloud.githubusercontent.com/assets/7445103/8369457/0288ec76-1b88-11e5-99d2-ecc5f8a5d596.png)

**Comment by drenfr01** [comment]
deployed in v2.2
