### ISSUE TITLE
App Event Submission not working on Desktop Google Chromes

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#239]
I have been unable to get the App to submit Events on Desktop Google Chromes for both Roxanne Browne and Lizelle Reed's accounts. Each time it just spins at "Checking In". I have tried every combination of Event entry:
- With and without photo
- Selfie and pre-existing event
- With and without Geolocation
- In regular and Incognito Chrome modes
![img_1929](https://cloud.githubusercontent.com/assets/7445103/8514832/8695494e-2365-11e5-930a-6d82b491d73d.JPG)
![img_1930](https://cloud.githubusercontent.com/assets/7445103/8514841/a1f90428-2365-11e5-837a-475bd1d4979f.JPG)
![img_1931](https://cloud.githubusercontent.com/assets/7445103/8514844/a87f02d4-2365-11e5-8d56-32bb34fd1425.JPG)
![img_1935](https://cloud.githubusercontent.com/assets/7445103/8514847/af38ecfc-2365-11e5-9010-aa8a39e29752.JPG)

**Comment by drenfr01** [comment]
@unioncapitalboston  This one we definitely want to try and recreate, given it's submitting via a browser

**Comment by drewproud** [comment]
@ballek - I am unable to reproduce this bug, though I suspect that this is a direct result of the performance issues that we have been having. Let's reopen this if it happens again after the performance fixes have been pushed to production.
