### ISSUE TITLE
joseyrenaud@hotmail.com account has taken over the Admin Page!

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#240]
![img_1936](https://cloud.githubusercontent.com/assets/7445103/8514857/e2715280-2365-11e5-8313-629ca334c074.JPG)

**Comment by TylerSheffels** [comment]
The actual bug here is that you can navigate to the login screen while you are logged in, and then click "sign up".  This ends up just adding another email to the user currently logged in.

I have removed admin role for this email, and will correct the bug.
