### ISSUE TITLE
Slow loading pages - we can pay for higher speed if needed

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#243]
For members, the Events page is taking a while to load - sometimes 15-30 seconds or more
![img_1984](https://cloud.githubusercontent.com/assets/7445103/8609979/3ce0bbc2-267a-11e5-92ae-c6ef5235d4e5.PNG)

For Admin, the AllMembers and Images pages are taking a long time to load - sometimes 30-45 seconds or more. We can add Pagination if that improves it, so long as Resorting includes the unseen pages.
![untitled](https://cloud.githubusercontent.com/assets/7445103/8610002/8fe50756-267a-11e5-800c-9ec72427f5fd.png)

**Comment by drenfr01** [comment]
@unioncapitalboston  All Members is already on the list, we'll do images as well

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek  How do we feel about performance? Better, worse, the same?

**Comment by drenfr01** [comment]
consider using meteorhacks:fast-render to address this issue
