### ISSUE TITLE
Photo Album not accessible on Android phones

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#244]
iPhones users are able to take a photo or access their Photo Album. Android phone users are only able to take a photo. Can it be added for users to be able to access their Photo Albums on Android like with iPhone?
![img_2001](https://cloud.githubusercontent.com/assets/7445103/8610977/c1e85b74-2687-11e5-9974-849d1f238b2a.PNG)

**Comment by TylerSheffels** [comment]
This is a chrome bug/feature.  https://code.google.com/p/android/issues/detail?id=62220

This works on firefox (at least, most likely others as well), so that is a workaround.
