### ISSUE TITLE
Sort by Location on Check-In Screen

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#245]
As we are adding hundreds of events at a time, it's starting to really crowd the quick check in screen. Is there a way to sort the events by proximity, and limit it to, say, the 5 closest events? I think this would be a major UI/UX enhancement.

**Comment by drenfr01** [comment]
Will be in v2.3

**Comment by drenfr01** [comment]
@ballek @unioncapitalboston I believe this is no longer relevant because we're only doing events in the next 2 hours for check in. Can I close it?

**Comment by unioncapitalboston** [comment]
Yep!
