### ISSUE TITLE
admins need to be able to see users' email addresses

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#247]
when people are getting locked out and they don't know why, this would be helpful to help them reset their password.

**Comment by drenfr01** [comment]
@ballek where would be the best place for this? Should we put it in the all members template? I

**Comment by ballek** [comment]
@drenfr01 
<img width="710" alt="screen shot 2015-07-15 at 9 11 35 pm" src="https://cloud.githubusercontent.com/assets/7898004/8713391/2348a812-2b36-11e5-91e4-aa78f1fa6048.png"> it's not viewable on "viewMemberProfile" right now :(

**Comment by drenfr01** [comment]
You can now click in and see the member's email from the all members tab. Opening up a ticket for performance
