### ISSUE TITLE
Admin Speed/ Clearing out Photos

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#248]
In the member photo view, we have looottsss of photos. Are they slowing things down? Can they automatically delete after a week?

**Comment by drenfr01** [comment]
@ballek @unioncapitalboston The questions is do we want to delete photos? After we move to Amazon S3 storage, the cost of storing photos is almost negligible ($.03 per GB, so right now ~$.15 per month...) I think a better approach would be to only display images in the member photo view for the past week.

Then you could still view the old photos if you wanted in Amazon S3 or download them to a computer.

**Comment by drenfr01** [comment]
currently photos are not set to delete. I think we can manually delete photos whenever (given that even a Terrabyte of storage is only $30 / month we should be good for awhile).
