### ISSUE TITLE
allMembers Admin page is crashing

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#258]
![messages image 2130513195](https://cloud.githubusercontent.com/assets/7445103/8690880/1bc2a8c6-2a88-11e5-9c8c-1d8db9c19c4c.png)

**Comment by drenfr01** [comment]
this should be resolved with performance fixes, let's test again after v2.2

**Comment by drenfr01** [comment]
the performance is now better, though not great. I timed it at ~5 seconds to load or change columns / order.

**Comment by drenfr01** [comment]
closing for now
