### ISSUE TITLE
Denormalize events into transactions

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#268]
We currently have events and transactions in separate collections. This has the following problems:

1) for selfie or ad-hoc events we create a fake event, then link a transaction to it. This is silly, and more importantly makes analytics reporting more complicated (i.e. separating out real vs. ad-hoc events.)

2) more importantly, a lot of our performance issues (on the admin side) stem from having two completely separate transactions. So any time we want to report the number of points, we have to lookup each transaction THEN find the corresponding event. 

3) De-normalizing is just best practice in meteor, and this might be a good use case because we'll only ever have 1 event attached to a transaction. So there's no need to worry about a crazy 1-many nesting. 

@TylerSheffels @drewproud  Thoughts? (I already talked with Drew about it).

**Comment by drenfr01** [comment]
Okay, this is in progress. @drewproud for the CheckIn logic server side, I think we're okay because it only checks "real events", e.g non-adhoc / non-selfie events. Is that true?

**Comment by drenfr01** [comment]
need to have DB layer for updating events, basically has to find all transactions with that event and update them as well

**Comment by drenfr01** [comment]
okay, we're going to need one heck of a migration script. It has to denormalize all transactions that currently exist

**Comment by drewproud** [comment]
Yeah, this is going to be a beast. Working on it now.

1. I'm not going to remove the extra ad hoc events at this time. I'm not sure what else depends on them and I'm already about 10 hours deep on this, so we can figure that out later. I have, however, denormalized events into transactions. We should be able to remove them relatively easily in the near future.

2. I'm putting in functions that will automatically recalculate the user metadata (total points, events attended, and most recent check in) each time a transaction is inserted, approved, or deleted. This is necessary to prevent us from having to publish every single event and transaction to admins. These functions reside and will be called from the DB layer. We should be conscious to never call an insert or update directly from this point on - *always* use the DB layer. 

3. Yup.

**Comment by gpatkinson** [comment]
I ran into problems with analysis last weekend due to the separate
collections as well ...  aggregation pipeline requires one collection and
this would be more efficient to implement than more complex map-reducing.
So another vote for denormalizing (although sounds challenging).

GPA

**Comment by drewproud** [comment]
Addressed in PR #276

**Comment by drenfr01** [comment]
done and deployed to Pro
