### ISSUE TITLE
why not have digital town hall real time chats?

### ISSUE THREAD

**Issue by mrapawy** [drenfr01/unionCapital#270]
basically give a pulbic / private chat option for each event, where you can have people ask their questions, etc.

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek Thoughts? 

I know you wanted eventually to make Union Capital more social, and having the ability to have private chats OR especially event based chats would be pretty cool

**Comment by drenfr01** [comment]
re-opening this because it might be relatively low effort....
