### ISSUE TITLE
Event End Time is showing as Current Time!

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#281]
Hey all, one of our members pointed out this confusing bug... 
<img width="1280" alt="eventtime" src="https://cloud.githubusercontent.com/assets/7898004/9023601/d602f56a-3870-11e5-80fa-2e615da4930f.png">

**Comment by ballek** [comment]
@TylerSheffels this seems to be specific to CSV uploads... is there something that I'm doing wrong!?

**Comment by drenfr01** [comment]
@ballek @unioncapitalboston I believe I fixed this, but bringing it to your people's attention to re-test

**Comment by unioncapitalboston** [comment]
Thanks! Will make sure to check

**Comment by ballek** [comment]
<img width="1165" alt="screen shot 2016-07-08 at 2 03 08 pm" src="https://cloud.githubusercontent.com/assets/7898004/16696847/c0e69216-4514-11e6-89f6-2880f672da28.png">

@drenfr01 

it still seems to be an issue, but it could be on my side. should i be entering the time as a number with a significant digit? as in, should i enter 2.0 instead of 2 for hours?

**Comment by drenfr01** [comment]
@ballek does this still happen?

**Comment by ballek** [comment]
looks good on the preview: 
<img width="652" alt="screen shot 2017-09-25 at 9 43 32 pm" src="https://user-images.githubusercontent.com/7898004/30838636-b653d320-a23a-11e7-89dd-8cdd938b95d6.png">

still a little wonky when clicked out on the "more info" tab, but not a huge deal! 
<img width="1149" alt="screen shot 2017-09-25 at 9 43 19 pm" src="https://user-images.githubusercontent.com/7898004/30838642-c69272be-a23a-11e7-9892-7dfe5aacdabf.png">

**Comment by drenfr01** [comment]
@ballek I think this looks good even on the moreInfo tab now?

**Comment by ballek** [comment]
looks good! closing this
