### ISSUE TITLE
App 3.0 idea - is there a better place to post these? :)

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#286]
It would be great for Super Admin to be able to edit Member profile info for when they mistype their email address or demo stuff changes. For example, someone yesterday created an account with @apl.com instead of @aol.com but there is no way for us to fix it and they will not receive App notification emails.

**Comment by drewproud** [comment]
This is great place to post it. Just tag it with '3.0' and 'enhancement' so they don't get lost. You should be able to do so by clicking the 'Labels' link on the right hand side.

**Comment by unioncapitalboston** [comment]
Thanks!!

**Comment by drenfr01** [comment]
at some point we (most liklely me) should remember to move over the ideas we have in trello
