### ISSUE TITLE
Sorting Current Events for Quick Check-In

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#289]
Members aren't using the geolocation quick check-in feature--- I think that they are a bit bewildered by having so many options that present themselves on the landing page. 
![img_8052](https://cloud.githubusercontent.com/assets/7898004/9141109/26665852-3d04-11e5-8cff-98e75d76e25c.PNG)

Although in the future it would be nice to sort via user's location, in the short term could we only show events that are currently happening? That is to say, check the current time as within an acceptable window of events that are happening today. That way, it would be unlikely that more than a few events would be shown at a time.

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek similar to the other ticket, I believe now this is good because there should only be events within the next 2 hours. Correct?

**Comment by unioncapitalboston** [comment]
Yep!
