### ISSUE TITLE
Houston Admin not accessible

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#291]
This is embarrassing as it shows that I have not gone into Houston since the whole member-as-admin debacle, but the credentials for login are no longer correct!
<img width="1233" alt="screen shot 2015-08-01 at 3 06 42 pm" src="https://cloud.githubusercontent.com/assets/7898004/9141268/67aa98ea-3d05-11e5-8dde-8ba8fac5758a.png">

**Comment by drenfr01** [comment]
fixed by drew
