### ISSUE TITLE
We have our first NaN with the new App :(

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#303]
Dioneiris Medrano submitted for a pre-existing event which she attended for 4.5 hours. The auto points approval listed was blank and when I clicked approve it listed it as NaN, and her Points Total is now also listed as NaN. Thoughts on what happened and how to fix it?
![untitled](https://cloud.githubusercontent.com/assets/7445103/9840074/7c2961e0-5a59-11e5-8ca4-4a5edd6178c0.png)

**Comment by drenfr01** [comment]
@ballek @unioncapitalboston this is also closed?
