### ISSUE TITLE
DST is screwing up event times

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#317]

**Comment by drenfr01** [comment]
okay, the tentative plan here is to use moment().isDST(), and display everything in EST (i.e. winter time, -05:00 offset).

I'm thinking something long the lines of...

if(isDST) {
if(time).isDST...just display it
otherwise...add an hour to offset

else 
if time is DST...remove 1 hour
else...do nothing

**Comment by drenfr01** [comment]
@ballek @unioncapitalboston I think this is working now...

**Comment by ballek** [comment]
@drenfr01 oh -05:00................. never underestimate the power of user error. i've been uploading csvs with -04:00!!!!!! this absolutely works, THANK YOU DUNCAN!
