### ISSUE TITLE
Event Edits don't hold

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#319]
This seems to be specifically with regards to points... I recently changed an event to double points, and while approving checkins, the points were at 0! and there wasn't a way to edit! the horror!

**Comment by ballek** [comment]
<img width="311" alt="screen shot 2015-11-14 at 6 49 56 pm" src="https://cloud.githubusercontent.com/assets/7898004/11166419/89f747f6-8b00-11e5-8053-2a9766359830.png">

**Comment by drenfr01** [comment]
@ballek Hmm, so I tested this a bit and can't seem to duplicate the error.

Specifically, were you changing a points per hour event to 2x the points per hour, or changing a points per hour event to a static # of points? Or were you doubling the points of a static event?

**Comment by drenfr01** [comment]
@ballek @unioncapitalboston have you seen this happen recently?

**Comment by unioncapitalboston** [comment]
This doesn't seem to be an issue anymore but has the feature been fixed to enter an event for flat points (no matter the number of hours)? Maybe that is what was tripping this up?
