### ISSUE TITLE
Rosa Portillo account weirdly linked with a sub-admin account

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#325]
Gabrielle Witham (withamg@ebnhc.org) is a sub-admin on the App for Let's Get Movin - EBNHC. She thought she logged out of her account to create a new user account for Rosa Portillo but wasn't completely logged out. Rosa's account was created with her email address (rossaportillo26@gmail.com) but it became linked with Gabrielle's sub-admin account and she is unable to enter and earn points. Her account says it is linked with Gabrielle's account. Please completely delete Rosa's account throughout the enter app. If you need to delete Gabrielle's account please let me know so I can create a new one for her. Thank you!
![untitled](https://cloud.githubusercontent.com/assets/7445103/12282707/26882694-b96e-11e5-862a-f7b4437a0ca4.png)

**Comment by drenfr01** [comment]
went in through compose and removed the incorrect email address and the incorrect role from Rosa's account. Searching through the app and the DB though I could not find gabrielle witham by either her first, last, or email address. Is the account still there?

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek I assume this is fixed?
