### ISSUE TITLE
"Internal server error" message but Points still processing

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#326]
For some reason Points submissions for Events are posting an "Internal server error" message, but when I go check the accounts the Points are still processing and being added in to members' accounts. Is there something else going wrong on the back end?
![untitled](https://cloud.githubusercontent.com/assets/7445103/12708640/850f3b2a-c86f-11e5-9ab0-670990796da2.png)

**Comment by drenfr01** [comment]
@unioncapitalboston I checked the logs and there are a bunch of error messages surrounding an invalid account. 

Is this issue still occurring, or did it just happen during one session?

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek I assume this is fixed?
