### ISSUE TITLE
nalsi21@gmail.com new UCB App Account won't login

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#329]
It just freezes at the login screen on all devices. She created another account using nalsi21@hotmail.com and that also freezes on the login. Could this be because she created the account two weeks ago when we had the Invalid Entry bug due to the password change of "contact@"
![untitled](https://cloud.githubusercontent.com/assets/7445103/13131752/b39d516c-d5bb-11e5-9d6b-327275b1502f.png)

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek it looks like your intuition was correct, somehow when this user was created she wasn't assigned the correct role.

**Comment by drenfr01** [comment]
this problem may be deeper than just those 2, I found 33 users which don't have roles. I imagine this will cause problems for all of them.

db.users.find({roles: {$exists: false}}).count()

**Comment by drenfr01** [comment]
okay, some good and bad news. of the 33 users, 8 are those who weren't signing in with FB. And of the ones signing in with FB, all of them are deleted. 

Looking at the 8 users, we have: vfllamas@gmail.com, f.dequandria@yahoo.com, njeri.barrett@novartis.com, oliviergalette@yahoo.com, juana42674@gmail.com, nnba09@gmail.com, nalsi21@hotmail.com (note: I inadvertently deleted nalsi21@gmail.com, but it seems duplicative anyway).

So I'm going to try adding roles to those 7 accounts, and log a bug for the FB login.

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek I just reset nalsi21@hotmail.com password after running the above query, and I think it works. Could you have the others on that list test out their accounts?

**Comment by unioncapitalboston** [comment]
Thanks for digging into this so thoroughly. Follow-up on the 8 accounts:

- We have no record on our end of vfllamas@gmail.com - please delete
- I have notified f.dequandria@yahoo.com to try using the App again
- We have no record on our end of njeri.barrett@novartis.com - plus it is a Novartis account (weird). Maybe someone checking out the app? Please delete
- We have no record on our end of oliviergalette@yahoo.com - please delete
- I have notified juana42674@gmail.com to try using the App again
- We have no record on our end of nnba09@gmail.com - please delete

Any thoughts on where these mystery accounts are coming from?

The three account errors that we verified all happened on the same night at KIPP in early February. Weird.

**Comment by unioncapitalboston** [comment]
I had previously archived Nalsi's @hotmail account and kept her @gmail account. Should she now use the hotmail account or restart her gmail? Either way is fine. Currently she does not show up at all on the Super Admin Dashboard.
Thanks!

**Comment by drenfr01** [comment]
Either way works, I can unarchive her hotmail and it should work, or she
can re-create her gmail account.

As to the mystery accounts, I'm not sure. We should probably quickly enable
Google Analytics for the app so we have a reasonable idea about how many
people are visiting the site.

Cheers,
Duncan

**Comment by unioncapitalboston** [comment]
Thanks!

I think I'll have Nalsi start over with Gmail since she uses that account for email.

That'd be great to start Google Analytics.

Go ahead and close this issue unless there is anything else you want to make sure we capture here :)
