### ISSUE TITLE
app crashed at 9:11 pm on Sunday, march 6. see log output below

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#344]
Exception from sub transactions id JyWx8t2CDiJj2yNy6 TypeError: Cannot set property 'userId' of undefined
    at packages/underscore/underscore.js:848:1
    at Array.forEach (native)
    at _.each._.forEach (packages/underscore/underscore.js:105:1)
    at Function._.extend (packages/underscore/underscore.js:845:1)
    at [object Object]._handler (server/publications/transactions.js:18:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
    at [object Object].subscriptionProto._runHandler (packages/meteorhacks_kadira/lib/hijack/wrap_subscription.js:12:1)
    at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
    at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
Kadira: trace is not started yet
Exception from sub userData id REPhiGmjLwbF3Pcc8 MongoError: Can't canonicalize query: BadValue bad sort specification

**Comment by drenfr01** [comment]
@unioncapitalboston

**Comment by unioncapitalboston** [comment]
It appeared to happen as I searched for "Wilbur Brown" using the new pagination set-up on Admin

**Comment by unioncapitalboston** [comment]
When I clicked his name his account was completely empty: No name, profile info, or points

**Comment by drenfr01** [comment]
hmmm, it looks like the CPU spiked to over 100%

**Comment by unioncapitalboston** [comment]
Umm... what does that mean? :)

**Comment by drenfr01** [comment]
haha, just collecting data. I was just working on fixing some bugs, so I need to deploy this anyway

**Comment by unioncapitalboston** [comment]
Great! So try again in a couple minutes?

**Comment by drenfr01** [comment]
I hit a strange error on my local that might be the same one reported here. I went to the allMembers page, then went to view member profiles, then went back to all members page. However, the app seemed to freeze up and the spinner ran continuously. I didn't see any errors in the console beyond those generated by viewMemberProfile, the only visible errors I could see was sockjs connections timing out

**Comment by unioncapitalboston** [comment]
I just searched for Wilbur Brown again (I'm trying to add-in points for him) and got the same blank page. It appears the App is crashing again :( I will stop trying to do this, but it appears there is an issue with the All Members tab on the Admin page  
![untitled](https://cloud.githubusercontent.com/assets/7445103/13559576/aaac5220-e3e3-11e5-8e5e-46759db70605.png)

**Comment by unioncapitalboston** [comment]
It seems that I cannot look up member info for anyone and get the same blank page as above when I click their name

**Comment by drenfr01** [comment]
yup, I've fixed why that is, and I'm very close to fixing the issue you reported (I know what it is, just trying to find a graceful way of fixing it)

**Comment by unioncapitalboston** [comment]
HIGH FIVES!!

**Comment by drenfr01** [comment]
@unioncapitalboston this should be fixed, deploying now. What happened is that I forgot to add the appropriate subscription to the viewMemberProfile template. Then, I discovered that we re-used a template, the CheckPoints template, in both super admin (see the above viewMemberProfile template) and for members. The problem was that in the super admin context, the publication returned all transactions, ~50k, which would lock up the browser / cause issues.

**Comment by drenfr01** [comment]
I'm opening up a bug ticket to deal with the hack I put into place to fix it, because we should find a better way

**Comment by unioncapitalboston** [comment]
Go Team! Shall we close this ticket?
