### ISSUE TITLE
manage events still has performance issues

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#350]
they seem to occur when going to the past events. Start with implementing pagination to see if that helps

**Comment by drenfr01** [comment]
correction, even present events is pulling down waaay too much data

@unioncapitalboston @ballek just FYI, we're on it :)

**Comment by unioncapitalboston** [comment]
Booya!!

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek my understanding is this works pretty well now in Prod?

**Comment by ballek** [comment]
@drenfr01 yes! works great!

**Comment by drenfr01** [comment]
thanks!
