### ISSUE TITLE
Returning users are taken to Sign-In screen not Homepage even though they are signed in

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#351]
Members are getting confused because when they go back to use their UCB App on their phone it takes them to the Sign-in page even though they are signed in. Clicking the logo at the top takes them to their home screen but users don't know this, and they think they have to log-in again every time they use the App. This is since the weekend fixes - is there something that switched this and can be fixed? Thanks!

**Comment by drenfr01** [comment]
@unioncapitalboston I'm sure it was @drewproud who broke it, but on the off chance it was me...

Can you provide any more details? Because I've noticed that behavior when I'm logged into the app and deploy new code. Are members experiencing it now or was it just several days ago?

**Comment by unioncapitalboston** [comment]
Thanks @drewproud for ruining EVERYTHING!!!!

On my phone right now I am logged in. I close the window, open a new window, and type in ucbapp.org and it takes me to the login screen, adding "/login" to the site address. Instead of entering my email and password, I click the UCB logo at the top it takes me to my account homepage stating that I have 5,850 points.

I thought it was just an issue from redeployment as well, but it keeps happening and our members are getting confused by it too.

**Comment by drenfr01** [comment]
Boo! I'll look into it

**Comment by unioncapitalboston** [comment]
Thanks! Clearly this is the malicious work of @drewproud with help from @ballek

**Comment by ballek** [comment]
Soraya's iPhone S continually logs her out of her account on seemingly every action!

**Comment by drewproud** [comment]
Hmm... are you able to replicate with anyone else?

**Comment by drenfr01** [comment]
@drewproud I think this is related to the routing issue that occurs when you logout.
