### ISSUE TITLE
Points Reset Request for next Wednesday

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#352]
Posting in Github instead of emailing, even though it isn't a Github issue :)

Next Wednesday we are switching to the new Rewards Tier System that we have been prepping our members for.

On Wednesday 3/16, can all Points in Members Accounts be reset to 0 and their Event History listing be cleared? Can this be done without deleting any Member Accounts (I hope!)?

Should @ballek do a download of all Member Transactions prior to 3/16 so we don't lose that transaction data for analysis, or will that still be available in the database?

Thank you!!

**Comment by unioncapitalboston** [comment]
Thanks Duncan and Team!

User Accounts say "0" but on the Super Admin Dashboard it still lists members' previous points when they should all state 0 too.

@drewproud Duncan has been gone about an hour and I'm already bugging you! Is there a reason that Accounts still list all the points for Admin but list 0 for members? Can this be fixed so it is 0 for everyone as we get restarted?

Much thanks!

![messages image 1495994768
(https://cloud.githubusercontent.com/assets/7445103/13834287/3ac47d32-ebc4-11e5-9f55-92aad172454a.png)

![messages image 1661657253](https://cloud.githubusercontent.com/assets/7445103/13834290/46695c84-ebc4-11e5-93d9-80a5904ec9af.png)

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek we're good on this, correct?

**Comment by unioncapitalboston** [comment]
Yep!
