### ISSUE TITLE
Old Points are showing up in Member Accounts after 1st event is approved

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#353]
Heeeeey @drewproud - sooooo... All the Member Accounts were reset to 0 = great!

But - once a member enters in an event and it is approved, their old point totals revert back = not so great

For example, someone who previously had 20,100 points, now has 0, but when they enter an event for 100 points and it is approved, it then jumps to 20,200 points.

Can this be fixed and for points to be based solely off of Points Earned starting Wednesday, March 16?

Thanks!

**Comment by drewproud** [comment]
@unioncapitalboston it should be all set now. I nulled out the point totals being carried on the users' profiles, forcing them to recalculate correctly the next time a user checks their points.
