### ISSUE TITLE
Points are still a bit funky

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#354]
Thanks @drewproud for working on this on a Friday night - just like the rest of us UCBers!!

It looks like the Points sort of zeroed out: The events prior to March 16 are not listed anymore but the Point total prior to March 16 is still listed at the top. Here is an example from my test App account. I have two events from yesterday so my total points at the top should only be 400:
![image1](https://cloud.githubusercontent.com/assets/7445103/13895389/2abbb85c-ed49-11e5-84b4-3b5ca8dff22d.PNG)

And the Admin Point total list is still listing some members with their prior point totals:
![untitled](https://cloud.githubusercontent.com/assets/7445103/13895440/8dbd75f8-ed49-11e5-8389-923b3f303235.png)

**Comment by drewproud** [comment]
@unioncapitalboston okay, try one more time. I just deployed some new code.

**Comment by unioncapitalboston** [comment]
Lookin' good! Much thanks!!
