### ISSUE TITLE
Missing User and difficulty with Pagination

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#355]
This new user Nneka Hall created an account today and I approved an Event entry, but I cannot find her on any of the "All Members" pages of the UCB App. Plus, it is really hard to search for Members since the top search bar only sorts for members on that current page instead of all pages, which means I have to click through each page to find a member. Can the Search Bar be fixed to search and filter through all pages of members? Thanks!
![untitled](https://cloud.githubusercontent.com/assets/7445103/14194786/2b6b7cd8-f780-11e5-902f-cec3ce16adf7.png)

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek I believe this was fixed, correct?
