### ISSUE TITLE
Uh-oh! Semi-Duplicate App Accounts from same phone sign-up

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#356]
It appears that Nneka Hall's app account somehow merged with Juanita Powers app account. Both were created today using the same phone. One of our Diamond Leaders signed them up. I'm guessing they didn't fully log out of Nneka's app account (sometimes the App doesn't log out) before creating Juanita's app and they somehow merged together. Check out these two screenshots showing Juanita's new account with email missdazee2003@yahoo.com, but the App Account has Nneka's email address
![untitled](https://cloud.githubusercontent.com/assets/7445103/14195517/198fbe22-f788-11e5-9de2-4cab720d21d7.png)
![untitled](https://cloud.githubusercontent.com/assets/7445103/14195524/26933068-f788-11e5-9307-abd076596432.png)

**Comment by drenfr01** [comment]
first step, disable the sign in & sign out. then investigate why the routing puts people at the sign in screen. Finally put some server side logic into accounts so that you can't create an account while signed in (to complete eliminate the possibility of these merges)
