### ISSUE TITLE
Request for new Points Approval email message

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#360]
With the new App version can we change the auto email message from:

"Thanks for attending XXX!You have earned 100 points for your service!"

TO

"Thank you for attending XXX. You have earned 100 points for your community engagement!"

Please make sure there is space between the two sentences :) And don't send this approval message for the UCB Button.

Thanks!

**Comment by drenfr01** [comment]
Can do!

**Comment by drenfr01** [comment]
done
