### ISSUE TITLE
Member accounts being recreated (and multiple submissions)

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#361]
Due to the default screen for ucbapp.org being the Login screen even when members have an account and are already signed in, members are creating 'new' accounts with their same email address because they are confused that they don't already have one. Thankfully it just merges with their previous account and all the data is still there, but I imagine this causes glitches on the back end. And, when members create the account and click 'submit' multiple times it sends multiple confirmations, such as I received this morning :)
![img_3915](https://cloud.githubusercontent.com/assets/7445103/14613992/131db1a0-056d-11e6-83ff-30f85d338309.png)

**Comment by drenfr01** [comment]
@drewproud I'm getting some weird behavior on this, particularly during hot code-reloads
