### ISSUE TITLE
Please delete account franscheska.eliza@gmail.com entirely

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#362]
Something very strange happened when the account was created. It never finished creating and sent no auto-notifications. It crashes when trying to log into the account. Try it out - it's weird!

franscheska.eliza@gmail.com
Password: 12345

Once it is deleted we will have Franscheska create a new account.

**Comment by drewproud** [comment]
@unioncapitalboston this should be fixed - it turned out her account didn't have a role. Don't forget this board is public, so make sure she changes her password!

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek closing this ticket
