### ISSUE TITLE
Need to organize links on admin navbar

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#363]
Our navbar is getting a little crowded, so we need to start grouping things and putting them into dropdowns. 

@ballek @unioncapitalboston how do you want to group them? Are there any placeholders we should add?

![screen shot 2016-05-01 at 11 00 56 pm](https://cloud.githubusercontent.com/assets/508707/14946462/a76658d4-0ff0-11e6-88bd-ceea96adc9d9.png)

**Comment by ballek** [comment]
@drenfr01 perhaps have a 'members' tab and drop down between UCB members and Partner members?
