### ISSUE TITLE
"Unable to save your photo"

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#371]
I've never seen this error message before! Any idea why? Submitted by Danita Perry
![20160607_235704](https://cloud.githubusercontent.com/assets/7445103/15882437/7cbe4770-2d0c-11e6-9b56-ff4da3a13780.jpg)

**Comment by drenfr01** [comment]
@unioncapitalboston have you seen this error again or was it just a one-off thing?
