### ISSUE TITLE
Time bar is set at Zero but still states 1 hour

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#400]
![img_4608](https://cloud.githubusercontent.com/assets/7445103/16697876/aa948f2c-4519-11e6-9b92-b51a21de21db.PNG)

**Comment by unioncapitalboston** [comment]
But at other times is still set to 1 hour?
![img_4609](https://cloud.githubusercontent.com/assets/7445103/16698261/6d34bf1a-451b-11e6-820b-3759cf999045.PNG)

**Comment by drenfr01** [comment]
done.

**Comment by unioncapitalboston** [comment]
After discussing with @ballek can we have all Time Bars default set to 0.5 hours? That way no one mistakenly submits for 0.0 hours but also isn't defaulting to an hour for something that didn't last that long.
![messages image 844420479](https://cloud.githubusercontent.com/assets/7445103/17337568/3f120a62-58b1-11e6-9981-906e73b3a5db.png)

**Comment by drenfr01** [comment]
done

**Comment by drenfr01** [comment]
fixed and closed
