### ISSUE TITLE
Can we pleeeease have green bars time out? :)

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#401]
![messages image 747898460](https://cloud.githubusercontent.com/assets/7445103/16698111/aba13f7c-451a-11e6-8451-04756f31ff2e.png)

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek I ripped out our custom notifications code and put in a good, clean package (aka someone's code who's smarter than me). We'll need to tweak it based on feedback we get from our members though, I'm not sure how it will look on all mobile devices.

Eric, currently the timeout is set to 5 seconds, we can change that though if you'd like.

**Comment by unioncapitalboston** [comment]
5 seconds is great! We'll test it out - mucho thanks!
