### ISSUE TITLE
It's not letting me select and approve some Events

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#403]
![messages image 4116260832](https://cloud.githubusercontent.com/assets/7445103/16698235/4ee9918e-451b-11e6-969a-c7360cac8b28.png)

**Comment by ballek** [comment]
@unioncapitalboston fill out the points first, and then select the button to the left of points- is that correct @drenfr01?

**Comment by unioncapitalboston** [comment]
That's what I did, I think. Can you give it a shot? Also - UCB Button shouldn't show up for Reading, right?

**Comment by drenfr01** [comment]
@unioncapitalboston I suspect what you did is entered the points and then didn't tab out of the box. I can change it so that as soon as you enter a number you can approve stuff if you'd like.

**Comment by unioncapitalboston** [comment]
Yep - no prob!
