### ISSUE TITLE
First time- Home screen icons don't load

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#407]
https://photos.google.com/share/AF1QipPmMpe03oAh9pgu419e6hgVWdxOa4dKe4AqDPOMx5F8URxMohgoUrMTvbBL3pDOdQ/photo/AF1QipO14_HwGP9IbTJBjHOyLb0fV1gImwh8iDme7BQK?key=MGRTdHVBTGhiRXRPcU1IT21rMWREdFY1cU82UDF3

i've had this issue come up on multiple devices. the icons usually show up a few clicks later

**Comment by drenfr01** [comment]
@ballek I've seen this as well, I think it's a slow loading time but I'll look into it
