### ISSUE TITLE
Pre-listed event check-ins are going automatically to partner admin approval

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#409]
Even when there has been no partner specified.

**Comment by drenfr01** [comment]
@ballek lets test this out again when we deploy automation

**Comment by ballek** [comment]
@drenfr01 tested again, still occurring

**Comment by drenfr01** [comment]
@ballek mind re-testing?

**Comment by ballek** [comment]
@drenfr01 I checked this on the QA site, prelisted events seem to be kicking back an error
<img width="1280" alt="screen shot 2017-10-05 at 10 26 25 am" src="https://user-images.githubusercontent.com/7898004/31232359-aec78186-a9b7-11e7-94f3-8a7c1fdf61be.png">
