### ISSUE TITLE
Admin Scroll not appearing

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#410]
<img width="1208" alt="screen shot 2016-07-13 at 3 21 23 pm" src="https://cloud.githubusercontent.com/assets/7898004/16821307/80b8186e-4923-11e6-88d1-ba8c5798dd94.png">

same on events page, all members page, extended member info page, and approve points

**Comment by drenfr01** [comment]
@ballek when you say admin scroll, do you mean you just can't scroll on this page? I tried testing it on both QA and my local laptop using Chrome, and it worked fine....

Can you provide any more details? @unioncapitalboston have you seen this?

**Comment by ballek** [comment]
@drenfr01 working now! weird glitch i suppose
