### ISSUE TITLE
Selfie Events less than 2 hours are not submitting without a photo

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#411]
These should be allowed in our new version - thanks!
![img_4658](https://cloud.githubusercontent.com/assets/7445103/16844813/911d139e-49b4-11e6-9ab2-33afcc5298cd.PNG)

**Comment by drenfr01** [comment]
@unioncapitalboston Automation was just merged, I'll deploy it by Monday so you can retest

**Comment by unioncapitalboston** [comment]
Fab!

**Comment by drenfr01** [comment]
let's leave it open till you test

**Comment by ballek** [comment]
@drenfr01 still not allowed
