### ISSUE TITLE
New Approval Rule?

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#412]
Can we add in a new Points Approval Rule that any Event Submission (pre-listed or Selfie) dated more than a week prior must go to Super Admin for approval even if it lasts less than 2 hours? Our general rule is that events can be submitted for more than a week in the past, but there are extenuating circumstances (such as a broken phone) in which we allow it with permission and will want to approve it.
Thanks!

**Comment by drenfr01** [comment]
@drewproud thoughts?

**Comment by drenfr01** [comment]
@drewproud bump
