### ISSUE TITLE
way to indicate that events need feedback

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#414]
some sort of alert or notification on events that still need to be rated?

**Comment by drenfr01** [comment]
@ballek we probably need to be a bit more specific here. We don't have a "notification center" or page  yet, so our options are pretty much limited to the pop-ups. 

Would we want a pop-up to display on login if they have an unrated event?

**Comment by ballek** [comment]
@drenfr01 maybe the pop-up should display on the history tab, but it might be a bit maddening if the event doesn't distinguish itself

**Comment by drenfr01** [comment]
make pre-events that haven't had feedback red.
