### ISSUE TITLE
Frozen screen when I signed out

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#416]
I got this weird frozen screen when I signed out. Just an issue with my browser?
![messages image 2213295658](https://cloud.githubusercontent.com/assets/7445103/16934995/8567641e-4d29-11e6-917f-5ea25aec580a.png)

**Comment by drewproud** [comment]
I suspect this is related to #392. I'll take a look at it.

**Comment by drewproud** [comment]
This should be fixed - please reopen if this pops up again.
