### ISSUE TITLE
Quick questions for Wednesday's call

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#417]
- Has "Impersonate User" been set up yet in Super Admin? I can't find it
- Have Images not been transferred over to the Test site? How can we test to see if images load without crashing the page?
  ![messages image 1299195259](https://cloud.githubusercontent.com/assets/7445103/16935059/fdaff0b2-4d29-11e6-99ac-432d839e64af.png)

**Comment by ballek** [comment]
@unioncapitalboston Go to All Members and you can impersonate members there

**Comment by drenfr01** [comment]
@unioncapitalboston also new images will appear in QA, but I cleared out the images folder to speed up deployment. 

This is actually a pertinent question for our prod deploy though...can we clear out the old images?

**Comment by drenfr01** [comment]
note to Duncan: look at https://cyberduck.io/ to download all files or see these links to do it via CLI

http://stackoverflow.com/questions/8659382/downloading-an-entire-s3-bucket

http://serverfault.com/questions/84815/how-can-i-get-the-size-of-an-amazon-s3-bucket

**Comment by drenfr01** [comment]
delete all the prod images
