### ISSUE TITLE
Login screen "under construction" when already logged in, rather than going to homescreen

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#422]
Small but, but this is what the screen says when I go to http://union-capital-qa-46165.onmodulus.net/login but am already logged in
![messages image 859689560](https://cloud.githubusercontent.com/assets/7445103/17337613/85f1b0ea-58b1-11e6-9286-b5dbb41bd5a0.png)

**Comment by drenfr01** [comment]
@unioncapitalboston @drewproud we eliminated the /login route, so you will just be able to send people to ucbapp.com. There should be no reason to go to ucbapp.com/login

Right Drew?

**Comment by drewproud** [comment]
That is correct, users will have to change their bookmark to just https://www.ucbapp.org and make sure it isn't the /login route.

**Comment by drenfr01** [comment]
@unioncapitalboston I believe this too is done and closed
