### ISSUE TITLE
Admin Impersonation did not work for Kimaada Shelton - will try for other ones

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#428]
![messages image 2490301446](https://cloud.githubusercontent.com/assets/7445103/17468386/907e931e-5cf5-11e6-87a0-6dc4ae356f21.png)

**Comment by unioncapitalboston** [comment]
It also didn't work for Rawle Howard
![messages image 2778603611](https://cloud.githubusercontent.com/assets/7445103/17468437/1019495c-5cf6-11e6-9bda-17aefc95aa60.png)

**Comment by drenfr01** [comment]
admin personation does not work on Prod with same error oddly as image viewer (something about canApprove). However, it also fails on my local with a different error: "Couldn't find a template named "/" or "". Are you sure you defined it?"

**Comment by drenfr01** [comment]
test
