### ISSUE TITLE
Spinning Wheel of Death

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#429]
Seems to be a Location issue on all types of phones, both Android and iPhone
![screenshot_2016-08-08-07-57-44](https://cloud.githubusercontent.com/assets/7445103/17500946/5dcf874e-5da8-11e6-861e-46462e2fd956.png)

**Comment by drenfr01** [comment]
@unioncapitalboston did this get resolved?

**Comment by unioncapitalboston** [comment]
Yep! Close it out?

**Comment by drenfr01** [comment]
yes sir, thanks!
