### ISSUE TITLE
Member emails cannot be edited

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#430]
Today I tried to fix this email account today: edwardcoleman9761@gmail.cim and change to .com
When I clicked update at the bottom I got this error message. I tried several times and kept getting it
![img_4821](https://cloud.githubusercontent.com/assets/7445103/17500994/ae88de10-5da8-11e6-957f-d99d29e28f4d.JPG)

**Comment by drewproud** [comment]
The email could not be edited in this case because there is already an account with attempted new email in the system. I made a fix to surface that error to the user to provide better visibility in the future.

**Comment by unioncapitalboston** [comment]
Beautiful - thanks!
