### ISSUE TITLE
TBD message for Automatically Approved events

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#431]
Admin cannot process them and they are now in Approved Events for members and cannot be updated:
![img_4825](https://cloud.githubusercontent.com/assets/7445103/17501028/ef01b098-5da8-11e6-99b1-8fea5b20db3b.JPG)
![img_4825 2](https://cloud.githubusercontent.com/assets/7445103/17501031/f6a56952-5da8-11e6-8ee3-36fe34dec0bc.JPG)
![img_4828](https://cloud.githubusercontent.com/assets/7445103/17501037/fce55836-5da8-11e6-8c7b-6b2e46001129.JPG)

**Comment by drewproud** [comment]
Pushed a fix for this. All selfie events that have been added since 3.0 went live don't currently have points, so as soon as this fix is deployed, I'll run a script to patch them.

**Comment by unioncapitalboston** [comment]
Great - thanks! When I should let members know to expect this fix to show up in their accounts?

**Comment by drewproud** [comment]
We'll deploy it tonight - I'm working on getting one more fix in before the next deploy.

**Comment by unioncapitalboston** [comment]
Awesome! Thanks!!

**Comment by drenfr01** [comment]
@unioncapitalboston can you confirm this is resolved?

**Comment by unioncapitalboston** [comment]
Yep! Close it out?

**Comment by drenfr01** [comment]
done! Thanks
