### ISSUE TITLE
Member reported issue: "Internal Server Error" message

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#432]
Kassandra Ledesma (kassandraledesma8@gmail.com) reports that she keeps trying to enter for the pre-listed Zumba class and gets the "Internal Server Error" message. Is this an issue just with her phone/app or is it because it was an Event uploaded before the new App version and it is getting stuck in the system?
![img_3590](https://cloud.githubusercontent.com/assets/7445103/17540216/6a782d22-5e82-11e6-951f-3d258b341598.jpg)

**Comment by drenfr01** [comment]
@unioncapitalboston I suspect because it was an older event, per our conversation. Looking into a fix

**Comment by unioncapitalboston** [comment]
Correct. I don't think this needs to be Top Priority since most events on the App now have been entered post 3.0 being launched.
