### ISSUE TITLE
Unable to click Admin Points values

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#433]
I swear this isn't just me being a dummy (I hope)! All of the Admin Points have been autofilled but I can't click any of them to approve them. Instead I have to go into each box, delete the points and rewrite them. Any possible way to correct this glitch in which I can't click the boxes? Maybe just default that the boxes can always be clicked? Thank you!
![messages image 860117941](https://cloud.githubusercontent.com/assets/7445103/17561530/760dc13e-5ef4-11e6-91d6-99d671b1aaed.png)

**Comment by drenfr01** [comment]
this is not Eric being a dummy, it's my bad programming. 

Long story short, I need to fix how the checkbox responds. Kill the error checking on the checkbox and test out to make sure nothing weird can happen
