### ISSUE TITLE
There is some funky math going on with Partner Double Points

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#434]
For some reason Double Points for partners is only happening for some of the hours submitted each time. In this example, the 8 hours of Double Points plus Button should equal 1650 not 1050.
![messages image 2212794748](https://cloud.githubusercontent.com/assets/7445103/17722991/709a9c30-6404-11e6-9a69-affbdf37ff0c.png)

**Comment by drenfr01** [comment]
basically we have two options: we can either a) change the partner button to actually double the points per hour or b) create a new rule where if the event is less than an hour it's auto approved (i.e. adds 200 points + other bonuses) and if it's more than an hour it goes to partner admin

@drewproud
