### ISSUE TITLE
make sure there is a mapping from eventCategory to addOn

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#440]
for example, there should be no UCB button for reading events

**Comment by drenfr01** [comment]
note: no pre-listed event should have partner org checkbox

**Comment by drenfr01** [comment]
@unioncapitalboston my idea here is simply to have permissible event categories listed (i.e. whitelisted) for each add-on. E.g. UCB Button would have a list containing: "Adult Education Classes, ...".

My question here is: from the perspective of add-ons, can I simply group all selfie events together? Put another way, do we anticipate distinguishing amongst selfie event "categories" for add-ons (e.g. if a member indicates the category of "education" for a selfie event, would that ever impact what add-ons are displayed?)

**Comment by ballek** [comment]
@drenfr01 I don't think whole categories would be affected, only subcategories.

**Comment by drenfr01** [comment]
this was completed and now is also largely irreleveant
