### ISSUE TITLE
Member was able to submit multiple items of feedback

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#444]
<img width="1088" alt="screen shot 2016-08-26 at 1 47 08 pm" src="https://cloud.githubusercontent.com/assets/508707/18015012/ad8498e4-6b93-11e6-8c43-a6267fa1c95d.png">

**Comment by ballek** [comment]
tested this yesterday- able to submit multiple lines of feedback, but only given points once, so, whatevs!
