### ISSUE TITLE
android phone not loading events

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#445]
@ballek mind uploading the version number of the android?

**Comment by ballek** [comment]
![img_0814](https://cloud.githubusercontent.com/assets/7898004/18174695/714446b0-703c-11e6-823f-31138f8a2cb3.JPG)
![img_0815](https://cloud.githubusercontent.com/assets/7898004/18174704/759fc130-703c-11e6-8742-db16f0aabb52.JPG)
![img_0879](https://cloud.githubusercontent.com/assets/7898004/18174714/8144eee8-703c-11e6-8aa1-1a48419c7205.JPG)

@drenfr01 also found this bug on an iphone 4!
