### ISSUE TITLE
Pre-listed Events auto-approval rule change

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#450]
We've had members checking into multiple events at the same time. Can we change the rules for all Pre-listed events to the following:
- Max hours that a member can earn is the max of the event length. So if an event is listed as 2 hours long, but a members selects three hours, they will still only earn for the 2 hours
- Successful geolocation check-in is AUTO-APPROVED no matter how long the hours (up to the max listed for the event)
- All other submissions (no geolocation, with or without photo) must come to Admin for Approval, no matter the time length.
  That way we can avoid someone 'mistakenly' going to 8 museums at once on the same day for 7 hours each!
  ![messages image 1422609156](https://cloud.githubusercontent.com/assets/7445103/18481119/05b56fc0-79a9-11e6-948e-19e4f00240a2.png)

**Comment by drewproud** [comment]
@unioncapitalboston so just to clarify here:    

- Event attendance duration should be capped at the event duration
- For pre-existing events, the following constitutes auto approval:
  - geolocation
  - in geolocation range
  - current event
  - Adherence to category-based rules (max check ins, etc)
- The following now constitutes super admin approval for pre-existing events
  - No geolocation or not in range
  - Adherence to category-based rules (max check ins, etc)

With all other partner admin rules to remain the same.

**Comment by ballek** [comment]
@drewproud 


> Event attendance duration should be capped at the event duration
**Correct**
For pre-existing events, the following constitutes auto approval:
geolocation
**Correct**
in geolocation range
**Correct**
current event
**Here's where we ran into trouble, people were simply checking in to every event listed on the current screen**
Adherence to category-based rules (max check ins, etc)
The following now constitutes super admin approval for pre-existing events
No geolocation or not in range
**Correct**
Adherence to category-based rules (max check ins, etc)
**Correct, including here max hours, if button is applicable, and if partnerAdmin is checked**
With all other partner admin rules to remain the same.
**Yessir!**

**Comment by drewproud** [comment]
@ballek okay, so the fact that all of those rules have a big fat AND in between them should fix the issue you mentioned, right?

**Comment by ballek** [comment]
let ME dust off my logic chops here

pre-existing event verified if: 
Geolocated AND/OR in Geolocation range AND only verifies for up to max duration
current event AND photo attached AND only verifies for up to max duration

pre-existing event sent for admin approval if:
No geolocation AND no photo

Also, for pre-listed events, Partner Organization Event Shouldn't even be an option to select since we will preload that information. I think the max checkins, max hours, button, partnerAdmin are really going to be more relevant for the selfie event approval process

**Comment by unioncapitalboston** [comment]
Thank you Duncan & Drew for working on this!

For quick access here is the link to the detailed Rules List. Most of them are the same, but there are a couple distinct ones as you have noted. Please keep sending along other clarifying questions and thanks!

https://docs.google.com/a/unioncapitalboston.com/spreadsheets/d/1sGNgaY24lMbA95dvwoPrTSNMC1o0ilwo6h6qaiKay8U/edit?usp=sharing

**Comment by drewproud** [comment]
@ballek okay, so to be clear here: is partner admin approval not a thing anymore? Just super admin?

**Comment by unioncapitalboston** [comment]
Partner Admin approval is still a thing, it's just that in the preloaded events we will indicate whether an event is worth 200 points per hour or not. The problem currently is that a Partner Event gets uploaded that is worth 200 points but the 'Partner Event' button is there to still earn another 100 points per hour. When someone goes to check-in at that pre-listed event and clicks the 'Partner Event' button they now automatically receive 300 points for the hour instead of 200. Can that 'Partner Event' button be removed for all pre-listed uploaded Events? But still have it there for Selfie Events? Thank you!

**Comment by drewproud** [comment]
@unioncapitalboston sounds good. In my PR, I've done the following:

1. Removed 'Partner Organization Event' addon for all pre-listed events.
2. Changed pre-existing event check-ins without in-range geolocation to partner admin approval.

Sounds right?

**Comment by ballek** [comment]
@drewproud looks good! youda best!
