### ISSUE TITLE
Both UCB Button and Partner Event buttons are now missing on all events, both pre-listed and Selfie

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#452]
Please keep the Partner Event button OFF of pre-listed events, but add back in the UCB Button.
Please add back in both the UCB Button and Partner Event button for Selfie Events.
Thanks!
![messages image 1113899285](https://cloud.githubusercontent.com/assets/7445103/22438950/cda84f06-e6fb-11e6-96e7-223b78fc2176.png)
![messages image 4256526954](https://cloud.githubusercontent.com/assets/7445103/22438951/cdb33a7e-e6fb-11e6-887c-26349fa45e9d.png)

**Comment by drenfr01** [comment]
@unioncapitalboston @ballek Good news, this looked like a simple seed data issue (i.e. the data in our DB that determines which events UCB button appears on). I updated the events that the UCB Button will appear on to the following...please test / check and let me know if it's correct?:

          'In-school Meeting','In-school Event','In-school Volunteer',
          'Chaperone Field Trip/Sport Activity', 'Adult Education Class', 'Library/Education Center',
          'Early Childhood Playgroup', 'Running, Biking, Team Sport', 'Gym/Fitness Center Exercise',
          'Health Center Appointment','Hospital Visit','Fitness Class','Health Workshop',
          'Farmers Market',
          'FII Monthly Meeting','Lending Circles Meeting','Financial Workshop','Home Buying Workshop/Class',
          'Financial Advisor Meeting','Opening New Bak Account','Tax Services','Volunteer: Organization',
          'Volunteer: Event','Volunteer: Helping Others','Performance/Festival','Workshop/Info Session',
          'Community Meeting','Leading/Teaching an Event/Workshop','Voter Registration/Engagement',
          'Advocacy Event/Rally', 'Political Activity','Donating clothing/goods','OTHER: Type in Description'

**Comment by drewproud** [comment]
Did it work before? Not sure why the changes would effect that

**Comment by ballek** [comment]
while we're on this one- what can i do about creating new selfie event categories in the future? every time i've attempted on Houston i come up empty handed D:

**Comment by ballek** [comment]
@drenfr01 in testing- 
![img_1611](https://cloud.githubusercontent.com/assets/7898004/22628554/f71b1e84-eba3-11e6-81e2-8b9fa9707f05.PNG)

**Comment by unioncapitalboston** [comment]
The "UCB Button" option is back for Pre-listed Events - thank you!
But both the "UCB Button" and "Partner Organization" buttons are still missing for Selfie Events:
![messages image 765806694](https://cloud.githubusercontent.com/assets/7445103/22694341/ddd2e246-ed14-11e6-8016-33f7b74f871c.png)
