### ISSUE TITLE
Massive submissions for 8 hours still being auto-approved

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#453]
Please take a look at Modesta Herrera's account. It is insane. She has been able to submit events that have no eligibility and get them auto-approved for 8 hours again and again. She is clearly confused, but since it auto-approves, she must think it is allowed. Here is an example from today, which means the auto-approvals for events over 2 hours are still occurring :(
![messages image 1624917439](https://cloud.githubusercontent.com/assets/7445103/22534864/269579d4-e8c5-11e6-8f61-12cd777a72ed.png)

**Comment by drenfr01** [comment]
@drewproud Hey drew, so I'm 95% sure this is the bug fix, but wanted to double-check. Looking at the checkInRules, I see that the auto block of the const PERMISSION_RULES has an block which has:

line 60, checkInRules.js
{
IS_RECOGNIZED_EVENT: true,
      IS_CURRENT_EVENT: true,
      HAS_GEOLOCATION: true,
      IN_RANGE: true}

I believe that also should have SATISFIES_AUTO_SELFIE_RULES: true in that block. Anecdotally with testing this seems to fix the problem?

**Comment by drewproud** [comment]
But this is a selfie event, no? It should fail IS_RECOGNIZED_EVENT if so.

**Comment by drenfr01** [comment]
@drewproud Excellent point, let me check.

**Comment by ballek** [comment]
@drenfr01 @drewproud FORGIVE MY IGNORANCE AND BUTTING IN but does IS_RECOGNIZED_EVENT relate to the adHoc descriptor? that field never seems to be captured on selfie transactions, could be contributing to to problem?

also THANK YOU GUYS SO MUCH you're saving us from literal bankruptcy right now haha

**Comment by drenfr01** [comment]
@ballek @unioncapitalboston @drewproud okay, so I looked at Herrera's account. She keeps submitting selfies that have a category of "OTHER: type in description".

Does anyone know how that's possible? When I go to the selfie events page I just get the four categories: education, finance, etc.

**Comment by unioncapitalboston** [comment]
Thanks Crew for working on this! The "OTHER: type in description" is a sub-category within "Community". Is this a missed category that is simply Auto Approving anything and everything that is submitted to it? Can we fix that ASAP? ALL "OTHER" submissions should go to Super Admin for approval, no matter the number of hours or photo.
![messages image 3343779411](https://cloud.githubusercontent.com/assets/7445103/22651427/03cdd9fc-ec51-11e6-92d5-0ff412dce351.png)

**Comment by drewproud** [comment]
@unioncapitalboston is this one good to close now?

**Comment by ballek** [comment]
@drewproud yes! works great now!
