### ISSUE TITLE
Please delete the Mayors Youth Council app version

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#455]
It looks like we are still being charged by Modulus for that App. They are no longer paying us for it and I don't believe are using it - please delete the entire app and discontinue the charge coming from Modulus. Thank you!
![messages image 2694910527](https://cloud.githubusercontent.com/assets/7445103/22627106/19d615ec-eb8a-11e6-96d7-7ac2147726f0.png)

**Comment by drenfr01** [comment]
@unioncapitalboston Done. I stopped the Modulus instance, and it will no longer charge us. Note: we'll still have the data for this instance if we need it, there is no additional cost for the storage above what compose already charges us.
