### ISSUE TITLE
2 final App fixes and we're groooovy!

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#461]
Greetings Duncan and Drew! I'm back from Taiwan - we somehow survived the 14 hour flights with a 5 year old and 2 year old :)

The App is rolling along swimmingly - thank you! There are still two final lingering issues from the 3.0 upgrade. Once fixed I think we should be all set!! Are you able to push these quick fixes sometime soon?
1) Add the UCB Button option back again for Selfie Events. No need to add the Partner Organization Event button back.
2) Unfreeze the Points boxes in the Pending Approval Admin page and unfreeze the page scroll ability after the Image box has been selected (these are in prior issue notes).

Much thanks and appreciation!

Eric

**Comment by drewproud** [comment]
Sounds good, I'm not familiar with issue 2 but I'd like to get these fixes out. I'll check them out this weekend.

**Comment by unioncapitalboston** [comment]
Thank you Drew!! @ballek can you explain Issue 2 a bit more? My lingo is limited :)

**Comment by ballek** [comment]
@drewproud thanks Drewby! Mass approval of points by superadmin isn't working great right now for two reasons- 
1. boxes cannot be selected until their value has been changed, currently we are deleting the value, replacing it with another value, then writing in the original value. 
2. the scroll function for the page often freezes, which i assume has to do with the number of transactions on the page

**Comment by unioncapitalboston** [comment]
Thanks Drew for cranking this out!
I noticed this evening while approving points that Partner Points Approval buttons have been unfrozen, but SuperAdmin Points Approval buttons are still frozen. Can that be fixed or will show up when @drenfr01 deploys it?

**Comment by drewproud** [comment]
Just made changes that should address the UCB button for selfie events (which should already be in production) and removed the disabled state from the checkboxes (which will go out with the enxt deploy).

I wasn't able to replicate your second issue @ballek - are there usually more transactions waiting for approval? There seemed to be only ~100 now.

**Comment by drewproud** [comment]
The changes to the approval page shouldn't be visible until we deploy @unioncapitalboston

**Comment by ballek** [comment]
@unioncapitalboston the partner admin buttons were unfrozen already, i thought that maybe the volume of selfie events had something to do with it, but i look forward to drew's deploy :) 

@drewproud the freezing usually can be fixed with a reload of the page... it tends to happen when i have too many pages open at once, which makes sense. not a top priority!
