### ISSUE TITLE
Photo attachment not working on some browsers?

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#465]
In the last few days (both before and after leaving Xervo) several members have reported not being able to attach a photo to Event submissions. Instead they are getting the Spinning Wheel of Death. I just tried on my iPhone 7 Safari and it worked fine. Is there a way to see if some older versions or specific browsers are blocking photo attachments?
Here is one member's message as an example:
<img width="362" alt="messages image 1445526664" src="https://cloud.githubusercontent.com/assets/7445103/25159334/2e577fe8-247d-11e7-990b-463b0aa6e2ee.png">

**Comment by drenfr01** [comment]
seems pretty random for browsers.
