### ISSUE TITLE
Selfie Event submission date issue

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#466]
for the rules, make sure the logic is based on the event date and not the transaction date field. Use case: submitting on wed event for monday / tuesday but getting rejected

@ballek

**Comment by drenfr01** [comment]
I checked the code and it references the eventDate. Have you guys seen any specific error cases I could use to debug? @unioncapitalboston @ballek

**Comment by ballek** [comment]
so let's say i've sat down to enter my points for the week. i read to my dog today, great! 
![img_3133](https://user-images.githubusercontent.com/7898004/30677278-d6810ec8-9e58-11e7-9f7f-e11fd827d377.PNG) i log the selfie no problem. but i read to my dog yesterday too, let's log that! 
![img_3132](https://user-images.githubusercontent.com/7898004/30677282-e3c518ea-9e58-11e7-8d9c-d8de5e1bcfa6.PNG) 

booo!

**Comment by ballek** [comment]
@drenfr01 this is looking good on QA!
