### ISSUE TITLE
make sure event date shows on user history not trasnaction

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#467]

**Comment by drenfr01** [comment]
Basically this means that the date of the event should display on the user history tab rather than when it was submitted. I fixed this + went ahead and added both dates to the detailed tab that opens up when you click it. @ballek @unioncapitalboston

**Comment by ballek** [comment]
<img width="970" alt="screen shot 2017-09-28 at 12 08 40 pm" src="https://user-images.githubusercontent.com/7898004/30977541-cfa52998-a445-11e7-8e18-9b568e7680d2.png">
<img width="591" alt="screen shot 2017-09-28 at 12 08 46 pm" src="https://user-images.githubusercontent.com/7898004/30977543-d0ee1526-a445-11e7-8e7b-00579598128a.png">

I'm not sure I see where both dates are listed, they should be in the pop-out tab, no?

**Comment by ballek** [comment]
@drenfr01 looks good on QA!
