### ISSUE TITLE
No need to display eventDate time on admin approval screen

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#475]
Since we don't ask users what time the event occurred, the app always puts 12:00am. Could save us a little screen real estate! 
<img width="1137" alt="screen shot 2017-09-28 at 12 33 01 pm" src="https://user-images.githubusercontent.com/7898004/30978668-32ea12e0-a449-11e7-9bc1-2934602eaf98.png">

**Comment by drenfr01** [comment]
ready for testing in QA as of October 2 @ 10:30 pm EST

**Comment by drenfr01** [comment]
also changed this on checkpoints for the user, take a look

**Comment by ballek** [comment]
@drenfr01 looks great Duncan!

**Comment by drenfr01** [comment]
closed
