### ISSUE TITLE
Donating clothes (100 points)

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#476]
@unioncapitalboston @ballek what does this mean? should this category be limited to 100 points?

**Comment by ballek** [comment]
@drenfr01 correct- users can put in as much time as they want, but they'll only receive 100 points for this transaction.

**Comment by drenfr01** [comment]
got it, I'll create a new rule that limits the points to 100

**Comment by drenfr01** [comment]
this works on local, going to submit to QA for testing in the next push

**Comment by ballek** [comment]
<img width="1084" alt="screen shot 2017-11-25 at 1 37 05 pm" src="https://user-images.githubusercontent.com/7898004/33233667-7c096310-d1e7-11e7-94ad-10126bf9bfa3.png">

Put in for 2 hours- got 200 points!

**Comment by drenfr01** [comment]
this may be linked to the eventCatogories collection not being updated.

**Comment by drenfr01** [comment]
just tested this on QA, Put in 8 hours and got expected results

**Comment by ballek** [comment]
@drenfr01 woop! looks great!

**Comment by drenfr01** [comment]
fixed adn closed
