### ISSUE TITLE
Images submit on desktop but not on mobile

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#478]
this is what the image looked like when i tried to submit a photo on mobile
<img width="941" alt="screen shot 2017-10-12 at 9 28 21 pm" src="https://user-images.githubusercontent.com/7898004/31526371-581fb794-af94-11e7-9053-2b8268235e03.png">

here's what it looked like when i uploaded a jpg from desktop
<img width="1235" alt="screen shot 2017-10-12 at 9 29 27 pm" src="https://user-images.githubusercontent.com/7898004/31526385-73da9f94-af94-11e7-8ff2-b05357f516f4.png">

also wow v huge!

**Comment by ballek** [comment]
@drenfr01 @TylerSheffels mobile is working! but the photo is ginormous- any way to get an itty bitty preview? 
![img_24b5eb00db7d-1](https://user-images.githubusercontent.com/7898004/34222015-0f3c59d6-e588-11e7-9586-8a3fb73a396e.jpeg)

**Comment by drenfr01** [comment]
still saw this issue in 3.1.5 testing on QA (note, the image is ginormous on desktop too)

**Comment by TylerSheffels** [comment]
On the next deploy the image should be a reasonable size on whatever device you view it on.

**Comment by ballek** [comment]
![fymoqmi](https://user-images.githubusercontent.com/7898004/34526325-2a2fb43e-f070-11e7-97e6-c85bddbc9608.gif)

**Comment by drenfr01** [comment]
@ballek Hahahaha, where in god's name is that gif from??? Also I think we can close this one out, right?

**Comment by ballek** [comment]
@drenfr01 secret GIF vault. Close it out!

**Comment by drenfr01** [comment]
@ballek BOOM!
