### ISSUE TITLE
UCB logo on top right doesn't appear sometimes on hot code reloads 

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#83]
refreshing the page with the browser reload fixes it. the error is something about text/mime transmitted as HTML

**Comment by drewproud** [comment]
Fixed this issue with commit 9ba69c9 - needed to make the path in the navbar template relative by adding a `/`

**Comment by drenfr01** [comment]
@drewproud hey Drew, this bug seems to have regressed

**Comment by drenfr01** [comment]
this also occurs with the check-in button, particularly when you first load the application
